namespace MathfinderBot
{
    public static class Quotes
    {
        static readonly Dictionary<int, string> quotes = new Dictionary<int, string>()
        {
            { 0,  @"Remind yourself, $, that overconfidence is a slow and insidious killer."},
            { 1,  @"I remember days when the sun shone and laughter could be heard from the tavern."},
            { 2,  @"Ruin has come to our family."},
            { 3,  @"Prodigious size alone does not dissuade the sharpened blade."},
            { 4,  @"Leave nothing unchecked, there is much to be found in forgotten places."},
            { 5,  @"Behold the heart of the world! Progenitor of life, father and mother, alpha and omega! Our creator—and our destroyer, $!"},
            { 6,  @"The mighty sword arm anchored by holy purpose—a zealous warrior."},
            { 7,  @"Many fall in the face of chaos, but not $. Not today."},
            { 8,  @"The cost of preparedness—measured now in gold, later in blood."},
            { 9,  @"Monstrous size has no intrinsic merit, unless inordinate exsanguination be considered a virtue."},
            { 10, @"We are the flame"",they cry,""and darkness fears us!"},
            { 11, @"This sprawling estate—a mecca of madness and morbidity. $'s work begins."},
            { 12, @"The front line of this war is not in the dungeon, but rather, inside the mind."},
            { 13, @"Welcome home, $, such as it is. This squalid hamlet, these corrupted lands, they are yours now, and you are bound to them."},
            { 14, @"The bellows blast once again! The forge stands ready to make weapons of war." },
            { 15, @"And now the true test—hold fast or expire?" },
            { 16, @"There is a sickness in the ancient pitted cobbles of the old road, and on its writhing path you will face viciousness, violence, and perhaps other damnably transcendent terrors." },
            { 17, @"Great adversity has beauty—it is the fire that tempers the blade." },
            { 18, @"Slowly, gently, this is how life is taken." },
            { 19, @"Where there is no peril in the task, there can be no glory in its accomplishment." },
            { 20, @"Do not ruminate on this fleeting failure—the campaign is long, and victory will come." },
            { 21, @"A moment of valor shines brightest against a backdrop of despair." },
            { 22, @"Good fortune and hard work may yet arrest this plague." },
            { 23, @"You cannot learn a thing you think you know." },
            { 24, @"Ignorance of your enemy and of yourself will invariably lead to defeat." },
            { 25, @"This expedition, at least, promises success." },
            { 26, @"The great ruins belong to us, and we will find whatever secrets they hold." },
            { 27, @"This one understands that adversity and existence are one and the same." },
            { 28, @"At home in wild places, they are a stalwart survivor and a strict instructor." },
            { 29, @"Curiosity, interest, and obsession—mile markers on $'s road to damnation." },
            { 30, @"Alone in the woods or tunnels, survival is the same. Prepare, persist, and overcome." },
            { 31, @"Success depends on survival." },
            { 32, @"Shoot, bandage, and pillage—the dancing steps of war." },
            { 33, @"Failure tests the mettle of the heart, brain, and body." },
            { 34, @"True desperation is known only when escape is impossible." },
            { 35, @"To those with a keen eye, gold gleams like a dagger’s point." },
            { 36, @"Experimental techniques and tonics can overcome things a sharpened sword cannot." },
            { 37, @"Every creature has a weakness. The wise hero trains for what she will face." },
            { 38, @"Gilded icons and dogmatic rituals—for some, a tonic against the bloodshed." },
            { 39, @"A sharper sword, a stronger shield. Anything to prolong a soldier’s life." },
            { 40, @"A strict regimen is paramount, if one is to master the brutal arithmetic of combat." },
            { 41, @"To fight the abyss, $ must know it." },
            { 42, @"$ searches where others will not go, to see what others will not see." },
            { 43, @"A little hope, however desperate, is never without worth." },
            { 44, @"Adversity can foster hope and resilience." },
            { 45, @"The cobwebs have been dusted, the pews set straight. The Abbey calls to the faithful." },
            { 46, @"I see something long-absent in the sunken faces of passersby—a glimmer of hope." },
            { 47, @"I hope you see things that startle you. I hope you feel things you never felt before. I hope you meet people with a different point of view. I hope you live a life you’re proud of. If you find that you’re not, I hope you have the strength to start all over again." },
            { 48, @"Every cleared path and charted route reduces the isolation of our troubled estate." },
            { 49, @"Shattered and unmade! Or, perhaps, reborn?"},
            { 50, @"“The way is lit. The path is clear. We require only the strength to follow it."},
            { 51, @"As the light gains purchase, spirits are lifted and purpose is made clear."},
            { 52, @"Trouble yourself not with the cost of this crusade—its noble end affords you broad tolerance in your choice of means."},
            { 53, @"$ may fall, but their knowledge lives on."},
            { 54, @"Send $ to journey elsewhere, for we have a need of sterner stock."},
            { 55, @"Driving out corruption is an endless battle, but one that must be fought."},
            { 56, @"“All manner of diversion and dalliance await those who cross the threshold with coin in hand."},
            { 57, @"More arrive, foolishly seeking fortune and glory in this domain of the damned."},
            { 58, @"Tortured and reclusive—this one is more dangerous than they seem."},
            { 59, @"What better laboratory than the blood-soaked battlefield?"},
            { 60, @"Suffer not the lame horse—nor the broken man."},
            { 61, @"Wealth beyond measure, awarded to the brave and the foolhardy alike."},
            { 62, @"Those without a stomach for this place must move on."},
            { 63, @"Life—the greatest treasure of all."},
            { 64, @"All my life, I could feel an insistent gnawing at the back of my mind. It was a yearning—a thirst for discovery—which could be neither numbed nor sated."},
            { 65, @"The raw strength of youth may be spent, but $'s eyes hold the secrets of a hundred campaigns."},
            { 66, @"We are born of this thing, made from it, and we will be returned to it in time"},
            { 67, @"Death is patient, it will wait."},
            { 68, @"Death and demise—cause for celebration!"},
            { 69, @"As soon as I saw $, I knew adventure was going to happen."},
            { 70, @"Most will end up here, covered in the poisoned earth, awaiting merciful oblivion."},
            { 71, @"Even reanimated bones can fall—even the dead can die again."},
            { 72, @"Let me share with you the terrible wonders I have come to know."},
            { 73, @"The plume and the pistol—a fitting end to folly, and a curse upon us all."},
            { 74, @"Even the aged oak will fall to the tempest’s winds."},
            { 75, @"More dust, more ashes—more disappointment."},
            { 76, @"$ does this because it irritates you."},
            { 77, @"I smell brimstone. Or is that $?"},
            { 78, @"$ answered the letter—now like me, you are part of this place."},
            { 79, @"Curious methodologies and apparatus can calm even the most tormented soul."},
            { 80, @"Fan the flames! Mold the metal! We are raising an army!"},
            { 81, @"Great heroes can be found even here, in the mud and rain."},
            { 82, @"As life ebbs, terrible vistas of emptiness reveal themselves."},
            { 83, @"Strong drink, a game of chance, and companionship—the rush of life."},
            { 84, @"There is power in symbols. Collect the scattered scraps of faith and give comfort to the masses."},
            { 85, @"Can you feel it? The walls between the sane world and that unplumbed dimension of delirium is tenuously thin here."},
            { 86, @"Success, so clearly in view. Or, is it merely a trick of the light?"},
            { 87, @"So many young adventurers, so little propriety."},
            { 88, @"Be wary, triumphant pride precipitates a dizzying fall."},
            { 89, @"For my part, I travel not to go anywhere but to go—I travel for travel’s sake. the great affair is to move." },
            { 90, @"A whole new world. A dazzling place I never knew, but when I’m way up here, it’s crystal clear that now I’m in a whole new world with you."},
            { 91, @"When’s it my turn? Wouldn’t I love, love to explore that shore above? Out of the sea, wish I could be, part of that world."},
            { 92, @"There’s no mountain too great."},
            { 93, @"Adventure is worthwhile in itself."},
            { 94, @"Avoiding danger is no safer in the long run than outright exposure. Life is either a daring adventure or nothing."},
            { 95, "Would you tell me, please, which way I ought to go from here?”\n“That depends a good deal on where you want to get to.”\n“I don’t much care where –”\n“Then it doesn’t matter which way you go.”"},
            { 96, @"If we were meant to stay in one place, we’d have roots instead of feet."},
            { 97, @"The danger of adventure is worth a thousand days of ease and comfort."},
            { 98, @"Travel is fatal to prejudice, bigotry, and narrow-mindedness."},
            { 99, @"Why do you go away? So that you can come back. So that you can see the place you came from with new eyes and extra colors. And the people there see you differently, too. Coming back to where you started is not the same as never leaving."},
            { 100, @"Let us step into the night and pursue that flighty temptress, adventure."},
            { 101, @"It’s a dangerous business, $, going out your door. You step onto the road, and if you don’t keep your feet, there’s no knowing where you might be swept off to."},
            { 102, @"Traveling – it leaves you speechless, then turns you into a storyteller."},
            { 103, @"Jobs fill your pockets, but adventures fill your soul."},
            { 104, @"$ may not have gone where they intended to go, but I think they have ended up where they intended to be."},
            { 105, @"Cover the earth before it covers you."},
            { 106, @"And into the forest $ goes, to lose their mind and find their soul."},
            { 107, @"Shut up, live, travel, adventure, bless, and don’t be sorry."},
            { 108, @"Life shrinks or expands in proportion to one’s courage."},
            { 109, @"Sometimes getting lost is not a waste of time."},
            { 110, @"I travel because I become uncomfortable being too comfortable."},
            { 113, @"Go where you feel most alive."},
            { 114, @"It feels good to be lost in the right direction."},
            { 115, @"Life should not be a journey to the grave with the intention of arriving safely in a pretty and well-preserved body, but rather to skid in broadside in a cloud of smoke, thoroughly used up, totally worn out, and loudly proclaiming “Wow! What a Ride!"""},
            { 116, @"The gladdest moment in human life is a departure into unknown lands."},
            { 117, @"If you want to know the truth of who you are, walk until not a person knows your name. Travel is the great leveler, the great teacher, bitter as medicine, crueler than mirror-glass. A long stretch of road will teach you more about yourself than a hundred years of quiet."},
            { 118, @"It is never too late to be who you might have been."},
            { 119, @"Death may be the greatest of all human blessings."},
            { 120, @"We all die. The goal isn’t to live forever, the goal is to create something that will."},
            { 130, @"Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose."},
            { 131, @"To die will be an awfully big adventure."},
            { 132, @"I would rather die a meaningful death than to live a meaningless life."},
            { 133, @"There are far, far better things ahead than any we leave behind."},
            { 134, @"There is no cure for birth and death save to enjoy the interval. The dark background which death supplies brings out the tender colours of life in all their purity."},
            { 135, @"Death is more universal than life; everyone dies but not everyone lives."},
            { 136, @"You never know how much you really believe anything until its truth or falsehood becomes a matter of life and death to you."},
            { 137, @"The hour of departure has arrived, and we go our separate ways, I to die, and you to live. Which of these two is better only Gods know."},
            { 138, @"All goes onward and outward, nothing collapses, and to die is different from what any one supposed, and luckier."},
            { 139, @"When the ancients said a work well begun was half done, they meant to impress the importance of always endeavoring to make a good beginning."},
            { 140, @"Dare to be wise; begin! He who postpones the hour of living rightly is like the rustic who waits for the river to run out before he crosses."},
            { 141, @"Affairs are easier of entrance than exit; and it is but common prudence to see our way out before we venture in."},
            { 142, @"Amusement that is excessive and followed only for its own sake, allures and deceives us."},
            { 143, @"The world is satisfied with words, few care to dive beneath the surface."},
            { 144, @"Do you shovel to survive, or survive to shovel?"},
            { 145, "“I’ve never once thought about how I was going to die,” she said. \n “I can’t think about it. I don’t even know how I’m going to live.”"},
            { 146, @"It’s not down on a map, true places never are." },
            { 147, @"Asps... very dangerous. You go first." },
            { 148, @"What is $? A miserable little pile of secrets!" },
            { 149, @"Hide a stone among stones and a man among men." },
            { 150, @"The Runelords will return." },
            { 151, @"Keep watching the skies, $" },
            { 152, @"$ loses saving throw vs. shiny with a penalty of -5. $ takes 2d8 damage to the credit card." },
            { 153, @"Better to have one's skull crushed than to have one's spirit enslaved!" },
            { 154, @"Only the dead have seen the end of war." },
            { 155, @"It is better to be feared than loved, if you cannot be both." },
            { 156, @"It’s time to kick ass and chew bubble gum…and $'s all outta gum." },
            { 157, @"It’s a-me, $io!" },
            { 158, @"The sun went down with practiced bravado. Twilight crawled across the sky, laden with foreboding. I didn’t like the way the show started. But they had given me the best seat in the house. Front row center." },
            { 159, @"The right man in the wrong place can make all the difference in the world." },
            { 160, @"Would you kindly…" },
            { 161, @"Nothing is true, everything is permitted." },
            { 162, @"It’s dangerous to go alone, take $!" },
            { 163, @"Praise the sun!" },
            { 164, @"Do you like hurting other people, $?" },
            { 165, @"Stop right there, criminal scum!" },
            { 166, @"Do a barrel roll!" },
            { 167, @"A man chooses; a slave obeys." },
            { 168, @"Grass grows, birds fly, the sun shines, and brother, $ hurts people." },
            { 169, @"Stay awhile and listen!" },
            { 170, @"Good men mean well. We just don’t always end up doing well." },
            { 171, @"You have died of dysentery, but not really." },
            { 172, @"The greatest glory in living lies not in never falling, but in rising every time we fall." },
            { 173, @"If life were predictable it would cease to be life, and be without flavor." },
            { 174, @"When you reach the end of your rope, tie a knot in it and hang on." },
            { 175, @"Don't judge each day by the harvest you reap but by the seeds that you plant." },
            { 176, @"Do not go where the path may lead, go instead where there is no path and leave a trail." },
        };

        static readonly Dictionary<int, string> duality = new Dictionary<int, string>()
        {
            { 0, "The toughest battle you’ll ever fight in your life is the battle within yourself." },
            { 1, "Some of the greatest battles will be fought within the silent chambers of your own soul." },
            { 2, "The hardest battle you will ever have to fight is between who you are now and who you want to be." },
            { 3, "The only battle to win is the battle within, that place where we realize that we deserve to have and create all that we want in our lives." },
            { 4, "The battles that count aren’t the ones for gold medals. The struggles within yourself, the invisible, inevitable battles inside all of us, that’s where it’s at." },
            { 5, "I had to get out of there for my face showed too much, the war in my body was dragging me down. My feet refused to carry me over to him again. The wind of my life was blowing me away." },
            { 6, "I guess it takes one to know one, and two can play that game." },
            { 7, "Anywhere is dangerous if you carry danger with you." },
            { 8, "You drive me back down my desperation—that unclouded incurable never forgotten evil growing inside my life." },
            { 9, "He thought, this is hell, not being able to live with oneself." },
            { 10, "You asked me, how to get out of the finite dimensions when I feel like it. I certainly don't use logic when I do it. Logic's the first thing you have to get rid of." },
            { 11, "Suspicion always haunts the guilty mind." },
            { 12, "Absurdity and anti—absurdity are the two poles of creative energy." },
            { 13, "I want to be two people at once. One runs away." },
            { 14, "We think the fire eats the wood. We are wrong. The wood reaches out to the flame. The fire licks at what the wood harbors, and the wood gives itself away to that intimacy, the manner in which we and the world meet each new day." },
            { 15, @"We, all who live, have
A life that is lived
And another life that is thought,
And the only life we have
It's the one that is divided
In right or wrong." },
            { 16, "Ce qu'on appelle une raison de vivre est en même temps une excellente raison de mourir." },
            { 17, "Rebelling is just obeying in reverse." },
            { 18, "No tree, it is said, can grow to heaven unless its roots reach down to hell." },
            { 19, "I learned to recognise the thorough and primitive duality of man; I saw that, of the two natures that contended in the field of my consciousness, even if I could rightly be said to be either, it was only because I was radically both." },
            { 20, "Every explicit duality is an implicit unity." },
            { 21, "You can't have an up without a down. You can't have a left without a right. This is duality. If you have a problem, you must already have the solution. The question is, do you really want the solution, or do you want to perpetuate the problem?" },
            { 22, "He who conquers himself is the mightiest warrior." },
            { 23, "Sometimes, I am my own worst enemy." },
            { 24, "I'm gonna hunt my life down and grab it." },
            { 25, "I am not in competition with anyone but myself. My goal is to improve myself continuously." },
            { 26, @"Take someone who doesn't keep score,
who's not looking to be richer, or afraid of losing,
who has not the slightest interest even
in his own personality: he's free." },
            { 27, "Never compete with someone who has nothing to lose." },
            { 28, "If you want to find the real competition, just look in the mirror. After awhile you'll see your rivals scrambling for second place." },
            { 29, "Together, we form a necessary paradox; not a senseless contradiction." },
            { 30, "Beating the competition is relatively easy. Beating yourself is a never-ending commitment."},
            { 31, "The strongest people are not those who show strength in front of the world but those who fight and win battles that others do not know anything about." },
            { 32, "What we obtain too cheap, we esteem too lightly" }
        };


        static readonly Dictionary<int, (string, string)> duels = new Dictionary<int, (string, string)>()
        {
            { 0, ("$, it's time to duel!", "D-D-D-DUEL!") },
            { 1, ("The gauntlet has been thrown. Do you accept the challenge, $?", "Accept") },
            { 2, ("Is that all you've got, $? A few tricks and quick feet? That's no way to enforce your bold tongue!", "En garde!") },
            { 3, ("# has no time to spare while you eat cheese, $; prepare instead for death.", "Continue with this matter") },
            { 4, ("I am #, master of ships, champion cat gambler, and I challenge $ to a mortal up-fuckery!", "Okay.") },
            { 5, ("Murder? It is not easily done, $.", "Do Murder") },
            { 6, ("I like the dueling club scene, where $ and # fight with their wands.", "Wand Fight") },
            { 7, ("# thoroughly disapproves of duels. If $ should challenge them, they would take them kindly and forgivingly by the hand and lead them to a quiet place and kill them.", "Challenge #") },
            { 8, ("I find it rude to laugh at a man with a sword, $.", "Laugh") },
            { 9, ("It's time to end this, $.", "End This") },
            { 10, ("$, it would be embarrassing for me to fight you in your condition.", "Fight Anyway") },
            { 11, ("Ain't it like $ to bring a knife to a gunfight.", "Bring It") },
            { 12, ("Why kill you now, $, with no one here to see you fall?", "Fight me!") },
            { 13, ("What do you want, $?", "A Roll-off.") },
            { 14, ("Remember that favorite game of yours, $?", "Let's play.") },
            { 15, ("$, is your blade as sharp as your tongue?", "Is yours as dull as your wit?") },
            { 16, ("# and $ enter, but only one can leave.", "THUNDERDOME!") },
            { 17, ("I could've shot you down when you landed, but that would've been ridiculously easy. You see, $, like every great artist, I want to create an indisputable masterpiece once in my lifetime: The death of $, mano a mano, face-to-face, will be mine.", "Aight.") },
            { 18, ("Sounds a bit old-fashioned, doesn't it, pistols at dawn—that sort of thing—$?", "Indeed.") },
            { 19, ("# is ruthless. # is powerful. # has a single task: Kill $ in order to protect their win record.", "You won't.") },
            { 20, ("Where $ believes their defenses are most certain, from that direction # will strike.", "Don't be so dra—OH SHI") },
            { 21, ("Don’t wait to be hunted to hide, that was always $'s motto.", "I never said that.") },
            { 22, ("$ cannot hunt for #. $ can only surrender and become #'s prey.", "Nah.") },
            { 23, ("Fear is an excellent motivator. # finds that it really brings out the true ingenuity $.", "Fear not!") },
            { 24, ("\"You hunt... Your fellow creatures?\" $ asks, still in disbelief. \"Of course. A hunt is only as interesting as the prey is clever!\"", "Gasp!" )},
            { 25, ("That’s quite the specific search...'Sadistic Old-$-Murdering Witches'—I can’t even begin to imagine what that involves.", ">_>") },
            { 26, ("If you are frightened, be silent. Whining is for prey. It attracts #. And you, $, are not prey.", "I'm not scared.") },
            { 27, ("If $ can bleed, # can kill it.", "Nuh uh.") },
            { 28, ("Both the # and $ have one thing in common, the battle for survival, the struggle for sustenance.", "Survive!") },
            { 29, ("That's what # thought they were. A stalker of stalkers. A predator preying on $.", "You thought wrong.") },
            { 30, ("The fingers of # feel what will soon belong to his whole body. $.", "What the f—.") },
            { 31, ("$ had said that if a bird becomes different from the others—disfigured or wounded—it is more likely to attract a predator, so the rest of the flock will kill it, which is better than drawing in an eagle, who might take one of them in the bargain.", "Take Out #") },
            { 32, ("They're follwing $, about thirty feet back. They get down on all fours and break into a sprint. They're gaining on you...it's #", "Run For Your Life")},
            { 33, ("Whom to pray and whom to be a prey is all in your devotion, $", "Do Devotion") },
            { 34, ("If you pursue #, you are an ordinary person. If # pursues you, you are $.", "Oh no.") },
            { 35, ("A boomerang returns back to the person who throws it. But first, while moving in a circle, it hits $.", "Ow.") },
            { 36, ("Each arrow $ fires toward # carries its own target into the decidedly secret tangle", "Shoot Arrow") },
            { 37, ("$ has always been stealthily targeted by #.", "Conspire no more.") },
            { 38, ("The following ten throws went a variety of places, but # was getting closer. $ was laughing so hard they couldn't breathe.", "Catch Your Breath") },
            { 39, ("The means are inconsequential; only the ends matter, $", "Make Ends") },
            { 40, ("Why go to war when you can assassinate the key players of your enemies: $.", "Good luck.") },
            { 41, ("Terror made $ cruel...", "Commit Cruelty") },
            { 42, ("# will give $ nightmares to haunt their dreams long after # is gone.", "Spooky.") },
            { 43, ("\"$ never sleeps. They are dancing, dancing. They say that they will never die.\"", "That's right.")},
            { 44, ("\"$ doesn't haunt us. That's not how it works. They're present among us because we won't let go of them.\"\r\n\r\n\"I don't believe in $,\" # said, faintly.", "👻👻👻") },
            { 45, ("To be $ is to glimpse a truth that might best be hidden.", "True. 🐙") },
            { 46, ("\"There are no ghosts, but up here\"—# gestured toward their head—“it’s $.", "Drop from the Ceiling") },
            { 47, ("# does not change you, $. They *reveal* you.", "Excuse me?") },
            { 48, ("Sometimes you have to pick the dice up to put them down, $", "Wise.") },
            { 49, ("$, can anyone think and hit someone at the same time?", "Hit Someone") },
            { 50, ("$—If you're a true warrior, # doesn't scare you.", "They make me better.") },
            { 51, ("$ is a sin.", "A deadly one.") },
            { 52, ("# finds $ repugnant. They are filthy, They are gross, They are alienating...", "This means war!") },
            { 53, ("Competition brings out the best in $—and the worst in #.", "⚔️⚔️⚔️") },
            { 54, ("I am Anti-Life, the Beast of Judgment. I am the dark at the end of everything. The end of universes, gods, worlds... of everything. Sss. And what will you be then, $?", "I am hope.") },
            { 55, ("There is no competition of sounds between a # and a $.", "REEE") },
            { 56, ("If you gone come in second, you're just $", "😒") },
            { 57, ("$, winning isn't about finishing in first place. It isn't about beating #. It is about overcoming yourself.", "I'd rather beat #.") },
            { 58, ("$, If two people Roll-off, their destinies become intertwined. They'll remain a part of each other's lives no matter what.", "Wait, what are you—") },
            { 59, ("Without struggle, $ has no value.", "Struggle") },
            { 60, ("$ is the bad guy, right?\"\r\n\"Depends on who wins, I guess.\"", "Write History") },
            { 61, ("Testing $ can prove a massive failure for the antagonist.", "Good thing I'm the hero.") },
            { 62, ("Vilification, by its definition, creates an antagonistic struggle, a #-versus-$ mentality, that throws us all into a senseless battle-royale", "So be it.") },
            { 63, ("There is no denying that there is evil in this world, but # will always conquer $.", "Press ❌ to Doubt") },
            { 64, ("$ loses. $ always loses because $ has to play by the rules. # doesn't.", "Cheaters never prosper.") },
            { 65, ("# and not $ mark the forward progress of mankind.", "Through violence.") },
            { 66, ("\"A great battle is a terrible thing,\" $ said, \"but in the midst of blood and carnage, there is sometimes also beauty, beauty that could break your heart.\"", "Literally.") },
            { 67, ("The possibilities were endless. Battles would be fought against $. Wonders revealed. Many journeys. Many lands. Many joys. Many sorrows.", "But stories, all.") },
            { 68, ("$ may be trained, but I'm fighting for my family, my home, my freedom.", "I know Kung-fu.") },
            { 69, ("True courage is when you know you're beaten before you even begin, but you begin anyway and see it through to the end. You don't often win, but sometimes you do.", "Take Your Chances") },
            { 70, ("the sole aim of a Roll-off is to teach $ to handle violence and violent individuals; whether it is tactile, mental or spiritual", "I am ready.") },
            { 71, ("$, Don’t believe the negative criticisms. # is capable beyond measure", "Capable of what?") },
            { 72, ("$ must never lose focus. If # bends them, it is within contemplation we soar the sky", "Take Flight") },
            { 73, ("Not all wars are worth fighting. Sometimes $ just has to let it go.", "Fight a War") },
            { 74, ("$,\r\nA Roll-off is a powerful force. It cannot be bought. It cannot be taken or stolen. Although sometimes it must be fought for, it must be given freely.", "Roll-off!")},
            { 75, ("Is it easy?\r\nNo it ain’t\r\nCan I fix it?\r\nNo I cain’t\r\nBut $ sure ain’t gonna take it lyin’ down", "Stand Up") },
            { 76, ("$—when # shows your their true colors—believe them.", "I do.") },
            { 77, ("You'll never do a lot unless you try, $", "Try") },
            { 78, ("$, # cannot demolish you without your permission.", "Get Demolished") },
            { 79, ("Roll-offs create fighters. This is not a place for $.", "Fight!") },
            { 80, ("Roll-offs are a pathway to your glorious destiny, $. Don't push them away. Embark on them.", "Embark") },
            { 81, ("Tears of sadness will erase the pain of $", "No...you.") },
            { 82, ("Each of us has an inner battle. We fight for happiness, and to stay alive. We fight to pursue $.", "Fight") },
            { 83, ("It is extremely easy\r\nTo get caught in the trap\r\nOf expecting $\r\nTo fall into our lap", "Sit on #'s Lap") },
            { 84, ("If you fight, you shall be prisoned. If you don't fight, you shall be slaved.\r\n$'s life, $'s choice", "Decide") },
            { 85, ("$ had faced death enough to know they were facing it again. But for the first time in a long time, they weren't ready to die.", "Die") },
            { 86, ("It's not that which happens to $. It's that which they 'make it happen' out of it.", "Make it Happen") },
            { 87, ("The world is filled with broken places, $. Pick your battles, and go win some.", "Pick a Fight") },
            { 88, ("Every $ you climb, leads you to a never ending destination of thriving gorgeously.", "Don't climb me.") },
            { 89, ("There's only so far $ can be pushed before they become their own hero.", "Become") },
            { 90, ("$ doesn’t fight fair.", "Nuh-uh.") },
            { 91, ("Don't allow $ to tell your heart what to do. $ gives up easily", "No I don't!") },
            { 92, ("If $ plans to build walls around themselves, know this—# will walk through them.", "You will try!") },
            { 93, ("If we don't roll for what we stand for with our dice and random-number-generators, do we really stand for anything?", "I—what?") },
            { 94, ("Conviction, $, is worthless unless they are converted into conduct.", "Conduct") },
            { 95, ("Are the things you are living for worth # dying for?", "They asked for it.") },
            { 96, ("# is a king so long as he has $ to look down on.", "The only king I see around here—is ME!") },
            { 97, ("At the end of the day, #'s ability to connect with $ comes down to how they make them feel.", "I feel like a Roll-off.") },
            { 98, ("Hope is the last thing a person does before they are defeated.", "Remain Hopeless") },
            { 99, ("Our world is not safe. It is a toxic swamp populated by # and $. The odds are stacked against us from the moment of conception.", "Hiss!") },
            { 100, ("$ looked like someone who could survive a couple of flesh wounds, but then so had Achilles and Caesar.", "🔪") },
            { 101, ("This person here, $, is just an absolute freak.", "👺👺👺") }

        };

        static readonly Dictionary<int, string> afterDuel = new Dictionary<int, string>()
        {
            { 0, "Tears shed for a lost Roll-off are not a sign of weakness—they are a sign of a pure heart." },
            { 1, "If you lose a Roll-off, do you stop saying you have one? Or do you always have a Roll-off, even if you lost it?" },
            { 2, "Have you ever lost a roll and wanted a match—one more chance to make up for the time when you thought you would win forever? If so, then you know you can go your whole life collecting days, and none will outweigh the one you wish you had back." },
            { 3, "\"You'll get over it...\" It’s the clichés that cause the trouble. To lose a Roll-off is to alter your life for ever." },
            { 4, "It's so much darker when a light goes out than it would have been if it had never shone." },
            { 5, "Life seems sometimes like nothing more than a series of lost rolls, from beginning to end. That's the given. How you respond to those lost rolls, what you make of what's left, that's the part you have to make up as you go." },
            { 6, "Don’t grieve. Any lost roll comes round in another form." },
            { 7, "The worst part of a lost Roll-off is not the pain. It's the humility of it. These events need not be shared." },
            { 8, "Whenever you should doubt your self-worth, remember the lotus flower. Even though it plunges to life from beneath the mud, it does not allow the dirt that surrounds it to affect its growth or beauty." },
            { 9, "You would always beat me; not so much because you are a better fighter as because you will not accept defeat." },
            { 10, "Revenge is possible only if you spare the enemy." },
            { 11, "Many people will tell you that it is not for a man to cry, but they may not know how it is to feel your head empty and only tears will come out to stand up for you." },
            { 12, "Falling and failing is needed if victory and triumph is your target." },
            { 13, "Hold yourself back, or heal yourself back together. You decide." },
            { 14, "You see—the strongest man in the world is he who stands most alone." },
            { 15, "Dice are to be rolled, not controlled; and thy humanity is won by continuing to play in face of certain defeat." },
            { 16, "But man is not made for defeat,\" he said. \"\r\n\r\nA man can be destroyed, but not defeated." },
            { 17, "My past has not defined me, destroyed me, deterred me, or defeated me; it has only strengthened me." },
            { 18, "Victory has a hundred fathers and defeat is an orphan." },
            { 19, "When defeat overtakes a man, the easiest and most logical thing to do is to quit. That is exactly what the majority of men do." },
            { 20, "Never stop just because you feel defeated. The journey to the other side is attainable only after great suffering." },
            { 21, "There was a saying that a man's true character was revealed in defeat. I thought it was also revealed in victory." },
            { 22, "In War: Resolution,\r\nIn Defeat: Defiance,\r\nIn Victory: Magnanimity\r\nIn Peace: Good Will." },
            { 23, "While one may encounter many defeats, one must not be defeated." },
            { 24, "Being challenged in life is inevitable, being defeated is optional." },
            { 25, "Some victories are merely defeat wearing the wrong clothing" },
            { 26, "Once you hear the details of victory, it is hard to distinguish it from a defeat." },
            { 27, "The most critical time in any battle is not when I’m fatigued, it’s when I no longer care." },
            { 28, "No one gives up on something until it turns on them, whether or not that thing is real or unreal." },
            { 29, "It is not defeat that destroys you,it is being demoralized by defeat that destroy you." },
            { 30, "I never thought of losing, but now that it's happened, the only thing is to do it right. That's my obligation to all the people who believe in me. We all have to take defeats in life." },
            { 31, "Victory attained by violence is tantamount to a defeat for it is momentary." },
            { 32, "I've always believed that the only defeats and victories that matter in life are those you lose or win alone, against yourself." },
            { 33, "I feel just, you know, defeated." },
            { 34, "Defeat is a state of mind; no one is ever defeated until defeat has been accepted as a reality." },
            { 35, "Opportunity...it often comes disguised in the form of misfortune or temporary defeat." },
            { 36, "When the odds are hopeless, when all seems to be lost, then is the time to be calm, to make a show of authority – at least of indifference."},
            { 37, "Always carry champagne! In victory You deserve it and in defeat You need it!" },
            { 38, "Victory settles a lot of arguments in most men's heads." },
            { 39, "You can’t win unless you try to win, but you can lose by trying not to lose." },
            { 40, "Winning may not be everything, but losing has little to recommend it." },
            { 41, "Sometimes the only way to win is to cheat." },
            { 42, "A strategic victory seen as luck by laymen." }


        };

        public static Dictionary<int, string> unfound = new Dictionary<int, string>()
        {
            { 0, "True wisdom is like an ocean; the deeper you go the greater the treasures you'll find." },
            { 1, "Once you find your treasure, the path to get there loses its importance." },
            { 2, "This world is a spider web of distractions - distracting us from that which is of the utmost importance." },
            { 3, "Perennial wisdom is found in the present moment." },
            { 4, "All experiences have hidden meanings." },
            { 5, "As long as we focus on the body-mind the truth will be concealed." },
            { 6, "Trials are treasure inside out." },
        };

        public static string Get(string characterName)
        {
            var r = new Random();
            var rn = r.Next(quotes.Count);
            return quotes[rn].Replace("$", characterName);
        }

        public static string GetDuality()
        {
            var r = new Random();
            var rn = r.Next(duality.Count);
            return duality[rn];
        }

        public static (string, string) GetDuel()
        {
            var r = new Random();
            var rn = r.Next(duels.Count);
            return duels[rn];
        }

        public static string GetAfterDuel()
        {
            var r = new Random();
            var rn = r.Next(afterDuel.Count);
            return afterDuel[rn];
        }

        public static string GetRedundant()
        {
            var r = new Random();
            var rn = r.Next(unfound.Count);
            return unfound[rn];
        }
    }
}
